version: '3'
services:
  redis_server:
    image: "redis:alpine"
    ports:
    - "6379:6379"
 
  node_server:
    image: jjasongao/telegram_bayareanews:node_server
    ports:
    - "3000:3000"
    links:
      - redis_server

  crawler:
    image: jjasongao/telegram_bayareanews:crawler
    links:
      - redis_server
 